### ISSUE TITLE
addition to executor service

### ISSUE THREAD

**Issue by apinto17** [BrianIshii/RecipeNetWithSQL#1]
we need a function in the executor service file that builds a select statement that:

takes:
  - table name, fields to expect, function, parameters

returns:
  - List<List<Field>> representing the returned fields

so in order to get the results from a query like:

    select name
    from User
    where levenshtein(name,  "Brian") < 5;

One would enter:

executor.select(User.TABLE_NAME, user.getFields("name"), Functions.LEVENSHTEIN, "Brian", "5")

using a function that looks like:

select(String table_name, List<Field> fields_to_expect, Functions functionType, String... parameters)

**Comment by sgilson** [comment]
Added. Example of use is the function 'fuzzyNameSearch' in the UserService
